import curses


print("======================================================")
print("================= Welcome to SADIE ===================")
print("=== Simple Android Download and Install Executable ===")
print("======================================================")
print("============= Made for the Rock64 board  =============")
print("============= by Matthew Petry (fire219) =============")
print("================== and Contributors ==================")
print("== Additional scripting by Kamil Trzciński (ayufan) ==")
print("======================================================")
print("")
print("SADIE version 1.1 (July 11 2017)")
print("")
print("This script will download and flash Android 7.1 to your Rock64 board.")
print("")
print("IMPORTANT NOTES:")
print("1. Before you continue, please locate a USB A-to-A cable.")
print("   It is critical to the installation process.")
print("")
print("2. If you wish to install Android to onboard eMMC, you *MUST* remove")
print("   your SD card if you have one.")
print("")
input('Press any key to continue.')
